name: Deploy

on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 300

  unit-tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - run: sleep 300

  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 300
