name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy-sandbox:
    name: Deploy to Sandbox
    runs-on: ubuntu-latest
    needs: tests
    concurrency:
      group: sandbox-deploy
      cancel-in-progress: false
    steps:
      - name: Running deploy
        run: sleep 120

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: tests
    concurrency:
      group: production-deploy
      cancel-in-progress: false
    steps:
      - name: Running deploy
        run: sleep 120

  deploy-api-docs:
    name: Deploy to Apiary
    runs-on: ubuntu-latest
    needs: tests
    concurrency:
      group: api-docs-deploy
      cancel-in-progress: false
    steps:
      - name: Running deploy
        run: sleep 120
