name: Reusable Test Workflow

on:
  workflow_call:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    concurrency:
      group: tests-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - name: Run Tests
        run: sleep 2
