name: Tests and Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    concurrency:
      group: pr-tests-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - name: Run Tests
        run: sleep 10

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: tests

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    concurrency:
      group: production-deploy
      cancel-in-progress: false

    steps:
      - name: Deploying
        run: sleep 10
