name: Reusable Test Workflow

on:
  workflow_call:

jobs:
  lint-python:
    name: Lint python code
    runs-on: ubuntu-latest
    concurrency:
      group: lint-python-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3

  lint-js:
    name: Lint javascript code
    runs-on: ubuntu-latest
    concurrency:
      group: lint-js-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3

  build-backend:
    needs: lint-python
    name: Build backend image
    runs-on: ubuntu-latest
    concurrency:
      group: build-backend-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3

  build-frontend:
    needs: lint-js
    name: Build frontend image
    runs-on: ubuntu-latest
    concurrency:
      group: build-frontend-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3

  build-combined:
    needs: [build-backend, build-frontend]
    name: Build combined image
    runs-on: ubuntu-latest
    concurrency:
      group: build-combined-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3

  test-backend:
    needs: build-backend
    name: Run backend tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-backend-${{ github.head_ref || github.ref }}-${{ matrix.index }}
      cancel-in-progress: true
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7]
    steps:
      - name: Running ${{ matrix.index }}
        run: sleep 10

  test-frontend:
    needs: build-frontend
    name: Run frontend tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-frontend-${{ github.head_ref || github.ref }}-${{ matrix.index }}
      cancel-in-progress: true
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5]
    steps:
      - name: Running ${{ matrix.index }}
        run: sleep 7

  test-e2e:
    needs: build-combined
    name: Run E2E tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-e2e-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3

  test-vrt:
    needs: build-combined
    name: Run VRT tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-vrt-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Running
        run: sleep 3
