name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  print-variables:
    name: Print variables
    runs-on: ubuntu-latest
    steps:
      - name: Imprime variaveis
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event.repository.default_branch: ${{ github.event.repository.default_branch }}"
          echo "github.event.repository.master_branch: ${{ github.event.repository.master_branch }}"
          echo "github.event.head_commit.message: ${{ github.event.head_commit.message }}"
          echo "CANCEL_IN_PROGRESS: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}"

  lint-python:
    name: Lint python code
    runs-on: ubuntu-latest
    concurrency:
      group: lint-python-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3

  lint-js:
    name: Lint javascript code
    runs-on: ubuntu-latest
    concurrency:
      group: lint-js-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3

  build-backend:
    needs: lint-python
    name: Build backend image
    runs-on: ubuntu-latest
    concurrency:
      group: build-backend-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3

  build-frontend:
    needs: lint-js
    name: Build frontend image
    runs-on: ubuntu-latest
    concurrency:
      group: build-frontend-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3

  build-combined:
    needs: [build-backend, build-frontend]
    name: Build combined image
    runs-on: ubuntu-latest
    concurrency:
      group: build-combined-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3

  test-backend:
    needs: build-backend
    name: Run backend tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-backend-${{ github.head_ref || github.ref }}-${{ matrix.index }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7]
    steps:
      - name: Running ${{ matrix.index }}
        run: sleep 10

  test-frontend:
    needs: build-frontend
    name: Run frontend tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-frontend-${{ github.head_ref || github.ref }}-${{ matrix.index }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5]
    steps:
      - name: Running ${{ matrix.index }}
        run: sleep 7

  test-e2e:
    needs: build-combined
    name: Run E2E tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-e2e-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3

  test-vrt:
    needs: build-combined
    name: Run VRT tests
    runs-on: ubuntu-latest
    concurrency:
      group: test-vrt-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !(github.ref_name == github.event.repository.default_branch && (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'bugfix') || contains(github.event.head_commit.message, 'revert'))) }}
    steps:
      - name: Running
        run: sleep 3
